name: Sync to Gitee

on:
  push:
    branches:
      - '*'  # 监听所有分支的推送
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的提交历史
      
      - name: Set up Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # 设置Git凭证存储
          git config --global credential.helper store
          # 将Gitee凭证写入存储
          echo "https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com" > ~/.git-credentials
      
      - name: Add Gitee remote
        run: |
          git remote add gitee "https://gitee.com/uuhit/uuhitBlog.git"
          git remote -v
      
      - name: Push to Gitee
        run: |
          # 推送所有分支
          git push -u gitee --all -f
          
          # 推送所有标签
          git push -u gitee --tags -f